Update dev.yml

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -1,56 +1,30 @@
-name: Build Deploy Trigger Automation
+trigger-playwright:
+  name: Trigger Playwright Automation
+  needs: deploy
+  runs-on: ubuntu-latest
 
-on:
-  push:
-    branches:
-      - main
-
-jobs:
-
-  build:
-    name: Build Application
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Build
-        run: |
-          echo "================================"
-          echo "Building Application..."
-          sleep 5
-          echo "Build Successful"
-          echo "================================"
-
-  deploy:
-    name: Deploy to DEV
-    needs: build
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Deploy
-        run: |
-          echo "================================"
-          echo "Deploying Application to DEV..."
-          sleep 5
-          echo "Deployment Successful"
-          echo "================================"
-
-  trigger-playwright:
-    name: Trigger Playwright Automation
-    needs: deploy
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Trigger Automation Repository
-
-        run: |
-          curl -L \
+  steps:
+    - name: Trigger Automation Repository
+      run: |
+        STATUS=$(curl -s \
+          -o response.txt \
+          -w "%{http_code}" \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/Gukapriyan/playwright-typescript-framework/dispatches \
-          -d '{
-            "event_type":"run-playwright"
-          }'
+          -d '{"event_type":"run-playwright"}')
+
+        echo "======================================="
+        echo "HTTP Status: $STATUS"
+        echo "======================================="
+        echo "Response:"
+        cat response.txt
+
+        if [ "$STATUS" != "204" ]; then
+          echo "Repository dispatch failed!"
+          exit 1
+        fi
+
+        echo "Repository dispatch successful!"
